input_samples: 
  - GFY-6_R1
  - GFY-7_R1
control: GFY-8_R1
reference_genome: PA01_GCF_000006765
fastp:
  qualified_quality_phred: 15
  unqualified_percent_limit: 40
  average_qual: 0
  length_limit: 0