input_samples:
  - Sample1
  - Sample2
  - Sample3
control: Sample3
reference_genome: ASM676v1
fastp:
  qualified_quality_phred: 25
  unqualified_percent_limit: 40
  average_qual: 20
  min_length: 50
macs3:
  qvalue: 0.01
  fragment_length: 200
  genome_size: 6264404
