input_samples: 
  - GFY-6_R1
  - GFY-7_R1
  - GFY-8_R1
control: GFY-8_R1
reference_genome: ASM676v1
fastp:
  qualified_quality_phred: 25
  unqualified_percent_limit: 40
  average_qual: 20
  min_length: 30
macs3:
  qvalue: 0.01
  fragment_length: 200
  genome_size: 6264404
