channels:
  - conda-forge
dependencies:
  - python=3.8
  - snakemake=6.10.0
  - pandas=1.3.3
  - numpy=1.21.2
  - bioconductor-deseq2=1.32.0
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - scikit-learn=0.24.2